; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:DEV-001-sensor-manager]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DDEV_001_SENSOR_MANAGER
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_rts = 0
monitor_dtr = 0

build_src_filter =
    +<*>
    -<app/*>
    +<app/hardware_manager.cpp>
    +<app/sensor_manager.cpp>
    +<app/data_manager.cpp>
    -<test/*>
    +<test/DEV-001-sensor-manager.cpp>

lib_deps =
  adafruit/Adafruit SHT31 Library@^2.2.2


[env:DEV-004-wifi-and-mqtt]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DDEV_004_WIFI_AND_MQTT
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_rts = 0
monitor_dtr = 0

build_src_filter =
    +<*>
    -<app/*>
    +<app/debug_logger.cpp>
    +<app/data_manager.cpp>
    +<app/wifi_manager.cpp>
    +<app/mqtt_client.cpp>
    -<test/*>
    +<test/DEV-004-wifi-and-mqtt.cpp>

lib_deps =
    knolleary/PubSubClient@^2.8

[env:DEV-005-status-indicator]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DDEV_005_STATUS_INDICATOR
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_rts = 0
monitor_dtr = 0

build_src_filter =
    +<*>
    -<app/*>
    +<app/status_indicator.cpp>
    -<test/*>
    +<test/DEV-005-status-indicator.cpp>

lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.5

[env:DEV-006-deep-sleep]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DDEV_006_DEEP_SLEEP
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_rts = 0
monitor_dtr = 0

build_src_filter =
    +<*>
    -<app/*>
    +<app/debug_logger.cpp>
    +<app/hardware_manager.cpp>
    +<app/runtime_manager.cpp>
    +<app/status_indicator.cpp>
    -<test/*>
    +<test/DEV-006-deep-sleep.cpp>

lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.5

[env:DEV-007-time-management]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DDEV_007_TIME_MANAGEMENT
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_rts = 0
monitor_dtr = 0

build_src_filter =
    +<*>
    -<app/*>
    +<app/time_manager.cpp>
    -<test/*>
    +<test/DEV-007-time-management.cpp>

[env:DEV-008-measurement-buffer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DDEV_008_MEASUREMENT_BUFFER
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_rts = 0
monitor_dtr = 0

build_src_filter =
    +<*>
    -<app/*>
    +<app/debug_logger.cpp>
    +<app/runtime_manager.cpp>
    +<app/time_manager.cpp>
    +<app/measurement_buffer.cpp>
    -<test/*>
    +<test/DEV-008-measurement-buffer.cpp>

[env:DEV-009-runtime-watchdog]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DDEV_009_RUNTIME_WATCHDOG
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_rts = 0
monitor_dtr = 0

build_src_filter =
    +<*>
    -<app/*>
    +<app/runtime_manager.cpp>
    +<app/debug_logger.cpp>
    -<test/*>
    +<test/DEV-009-runtime-watchdog.cpp>